# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np
arr = np.random.uniform(0, 20, (4, 7))
arr

array([[ 8.73447819,  5.84863988,  8.2111301 ,  4.28042944,  8.24197693,
         3.63189721, 13.60271661],
       [18.72972211,  6.87529674, 18.70577422,  5.89905774, 18.26859714,
        11.40456668, 18.50466671],
       [18.73450136,  2.39043365,  5.39458966,  4.21434716,  8.53649906,
        17.39895367,  8.04757744],
       [10.55380548,  3.96060473,  8.71900883, 11.60635146,  7.58151808,
         6.48528627,  3.22827213]])

Нормализация:

In [3]:
arr_new = (arr - arr.min()) / (arr.max() - arr.min())
arr_new

array([[0.38815579, 0.21158786, 0.35613512, 0.11563803, 0.35802246,
        0.07595805, 0.68601545],
       [0.99970759, 0.27440312, 0.99824235, 0.21467264, 0.97149399,
        0.55152323, 0.98593773],
       [1.        , 0.        , 0.18380712, 0.11159483, 0.37604258,
        0.91828548, 0.34612826],
       [0.49947002, 0.09606979, 0.38720931, 0.56386929, 0.31761276,
        0.25054061, 0.05126254]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [8]:
matrix = np.random.randint(0, 10, size=(8,10))
summ = np.sum(matrix, axis = 1)
index = np.where(summ == min(summ))
matrix, summ, index, matrix[index]

(array([[8, 2, 4, 1, 0, 8, 2, 6, 8, 2],
        [8, 7, 2, 2, 5, 2, 8, 8, 3, 6],
        [6, 2, 8, 1, 5, 6, 7, 8, 9, 5],
        [4, 9, 8, 4, 3, 9, 9, 0, 8, 5],
        [4, 4, 1, 0, 0, 3, 5, 8, 1, 7],
        [2, 1, 7, 8, 7, 1, 5, 3, 1, 2],
        [0, 3, 1, 7, 5, 8, 5, 0, 1, 5],
        [9, 9, 8, 6, 8, 6, 6, 2, 7, 1]]),
 array([41, 51, 57, 59, 33, 37, 35, 62]),
 (array([4], dtype=int64),),
 array([[4, 4, 1, 0, 0, 3, 5, 8, 1, 7]]))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [9]:
a = np.array([0, 0, 0, 30])
b = np.array([50, 40, 0, 10])
sum((a-b)**2)**0.5

67.08203932499369

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [10]:
A = np.matrix(
    [[-1, 2, 4], 
     [-3, 1, 2], 
     [-3, 0, 1]])

B = np.matrix(
    [[3, -1], 
     [2, 1]])

C = np.matrix(
    [[7, 21], 
     [11, 8], 
     [8, 4]])
x = np.linalg.inv(A)*(-C)*np.linalg.inv(B)
x

matrix([[ 1.00000000e+00,  5.32907052e-16],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [4]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
data[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
for i in range(1, data.shape[1]):
    print(f'#{i}: min = {data[i].min()} max = {data[i].max()}, mean = {data[i].mean()}')

#1: min = 7 max = 23891, mean = 7974.333333333333
#2: min = 6 max = 94746, mean = 31587.333333333332


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [6]:
quantile_75 = np.quantile(data[:, 1], 0.75)
new_data = data[np.where(data[:, 1] <= quantile_75)[0], :]
new_data, new_data.shape

(array([[127244,     60,     16],
        [ 23891,     25,      7],
        [ 94746,     10,      6],
        ...,
        [ 43407,     35,      7],
        [498432,     65,     15],
        [370915,      5,      4]]),
 (75461, 3))

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [7]:
data[:, 1] = np.where(data[:, 1] != 0, data[:, 1], 1)
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

In [8]:
np.where(data[:, 1] == 1)

(array([  345,   392,   411,   691,   700,   705,   706,   720,   728,
          793,   824,   840,   964,  1091,  1556,  1660,  1670,  1709,
         1740,  1805,  1836,  1931,  2171,  2228,  2269,  2339,  2393,
         2404,  2662,  2877,  3061,  3097,  3160,  3317,  3620,  3686,
         3836,  3914,  3944,  4057,  4100,  4163,  4413,  4431,  4641,
         4696,  4785,  4806,  5017,  5079,  5186,  5398,  5447,  5583,
         5623,  5807,  5858,  6051,  6251,  6259,  6401,  6546,  6583,
         6676,  6794,  7042,  7087,  7178,  7965,  8048,  8091,  8094,
         8106,  8390,  8393,  8693,  8792,  8879,  9239,  9249,  9360,
         9610,  9705,  9953,  9954,  9968, 10054, 10124, 10317, 10397,
        10486, 10606, 11274, 11376, 11776, 11911, 12098, 12131, 12424,
        12445, 12519, 12599, 12806, 12905, 13033, 13131, 13537, 13546,
        13711, 14026, 14161, 14380, 14587, 14590, 14763, 14918, 15205,
        15275, 15404, 15410, 15479, 15578, 15620, 15658, 15877, 15974,
      

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [9]:
len(np.unique(data[:, 0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [10]:
len(np.unique(data[:, 2])), np.unique(data[:, 2])

(37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [11]:
short_cut = data[np.where(data[:, 2] <= 5)[0]]
short_cut, short_cut.shape

(array([[446597,     15,      5],
        [204134,      5,      3],
        [ 25623,      6,      4],
        ...,
        [ 52088,     60,      5],
        [128811,     15,      4],
        [370915,      5,      4]]),
 (17262, 3))

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [12]:
max(data[:, 2]/data[:, 1]), data[:, 2]/data[:, 1]

(24.0,
 array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.1       ]))

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [13]:
sorted_indices = np.argsort(data[:, 1])[-100:]
sorted_array = data[sorted_indices]
sorted_array[:, 2].mean()

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [14]:
idx = np.random.randint(data.shape[0], size=10)
data[idx, :]

array([[170614,     20,      5],
       [517442,     15,     10],
       [ 49595,     60,     11],
       [140745,     25,      8],
       [427857,     15,      5],
       [ 47618,     55,      6],
       [349265,     30,     11],
       [250520,     75,     12],
       [215370,    120,     15],
       [424910,    127,      7]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [15]:
str(len(np.where(data[:, 2] < data[:, 2].mean())[0])/data.shape[0]*100) + "%"

'58.802%'

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [16]:
good_recepts = np.zeros((data.shape[0], 4), dtype=int)
good_recepts[:, :3] = data
good_recepts[np.where((data[:, 2] <= 5) & (data[:, 1] <= 20)), 3] = 1
good_recepts

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [17]:
str(len(np.where((data[:, 2] <= 5) & (data[:, 1] <= 20)))/data.shape[1]*100) + '%'

'33.33333333333333%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [18]:
short_recipes = data[data[:, 1] < 10]
standard_recipes = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_recipes = data[data[:, 1] >= 20]

max_length = min(len(short_recipes), len(standard_recipes), len(long_recipes))

three_dimensional_array = np.zeros((3, max_length, 3), dtype=int)

three_dimensional_array[0, :max_length, :] = short_recipes[:max_length]
three_dimensional_array[1, :max_length, :] = standard_recipes[:max_length]
three_dimensional_array[2, :max_length, :] = long_recipes[:max_length]

three_dimensional_array.shape, three_dimensional_array

((3, 7588, 3),
 array([[[ 67660,      5,      6],
         [366174,      7,      9],
         [204134,      5,      3],
         ...,
         [420725,      5,      3],
         [  4747,      1,      9],
         [370915,      5,      4]],
 
        [[ 94746,     10,      6],
         [ 33941,     18,      9],
         [446597,     15,      5],
         ...,
         [  9831,     15,      7],
         [335859,     12,     14],
         [256812,     10,      3]],
 
        [[127244,     60,     16],
         [ 23891,     25,      7],
         [157911,     60,     14],
         ...,
         [168901,     25,      7],
         [392339,     35,     13],
         [206732,     45,     10]]]))